export const COOKIE_NAME_NIP = "VE2UrvMEwISa3OaX5PV1";
export const COOKIE_NAME_NAMA = "N5vQVKYBZ5rYvNZNy888";
export const COOKIE_NAME_JABATAN = "zIlonrvNs8QKsCADIlc8";
export const COOKIE_NAME_GOLONGAN = "J7nciHPlbaZT6QTYhPI4";
export const COOKIE_NAME_PANGKAT = "7I4aPy0E98wABMR7A4IF";
export const EXPIRED_COOKIE = 10;
